-- This sql create table_2017 table.

CREATE TABLE IF NOT EXISTS PUBLIC.table_2017 (
    transactionID INTEGER UNIQUE PRIMARY KEY,
    gvkey INTEGER,
    companyName VARCHAR(250) NOT NULL, 
    companyISIN VARCHAR(250),
    companySEDOL VARCHAR(250),
    insiderID INTEGER,
    insiderName VARCHAR(250),
    insiderRelation VARCHAR(250),
    insiderLevel VARCHAR(250),
    connectionType VARCHAR(250),
    connectedInsiderName VARCHAR(250),
    connectedInsiderPosition VARCHAR(250),
    transactionType VARCHAR(250),
    transactionLabel VARCHAR(250),
    iid VARCHAR(250),
    securityISIN VARCHAR(250),
    securitySEDOL VARCHAR(250),
    securityDisplay VARCHAR(250),
    assetClass VARCHAR(250),
    shares VARCHAR(250),
    inputdate INTEGER,
    tradedate INTEGER,
    maxTradedate FLOAT,
    price FLOAT,
    maxPrice FLOAT,
    value FLOAT,
    currency VARCHAR(250),
    valueEUR FLOAT,
    unit VARCHAR(250),
    correctedTransactionID FLOAT,
    source VARCHAR(250),
    tradeSignificance INTEGER,
    holdings FLOAT,
    filingURL VARCHAR(250),
    exchange VARCHAR(250)
    )

